//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Viper Swift Xcode Templates. (A.Atamanskyi ©)
//

import Foundation

protocol ___VARIABLE_name___InteractorInput {}

final class ___VARIABLE_name___Interactor {

	// MARK: - Public properties

	// MARK: - Private properties

	weak var presenter: ___VARIABLE_name___PresenterOutput?

	init() {
		
	}

}

// MARK: - Input

extension ___VARIABLE_name___Interactor: ___VARIABLE_name___InteractorInput {}
