//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Viper Swift Xcode Templates. (A.Atamanskyi ©)
//

import Foundation

protocol ___VARIABLE_name___PresenterInput {}
protocol ___VARIABLE_name___PresenterOutput {}

final class ___VARIABLE_name___Presenter {

	// MARK: - Public properties

	// MARK: - Private properties

	private let router: ___VARIABLE_name___RouterInput
	private let interactor: ___VARIABLE_name___InteractorInput
	private weak var view: ___VARIABLE_name___ViewControllerOutput?

	init(router: ___VARIABLE_name___RouterInput, interactor: ___VARIABLE_name___InteractorInput, view: ___VARIABLE_name___ViewControllerOutput) {
		self.router = router
		self.interactor = interactor
		self.view = view
	}

}

// MARK: - Input

extension ___VARIABLE_name___Presenter: ___VARIABLE_name___PresenterInput {}

// MARK: - Output

extension ___VARIABLE_name___Presenter: ___VARIABLE_name___PresenterOutput {}
