//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Viper Swift Xcode Templates. (A.Atamanskyi ©)
//

import UIKit

protocol ___VARIABLE_name___ViewControllerOutput: class {}

final class ___VARIABLE_name___ViewController: UIViewController {
	
	// MARK: - Outlets

	// MARK: - Public properties

	var presenter: ___VARIABLE_name___PresenterInput!

	// MARK: - Private properties

	// MARK: - View controller lifecycle
}

// MARK: - Output

extension ___VARIABLE_name___ViewController: ___VARIABLE_name___ViewControllerOutput {}